### ISSUE TITLE
VSCode TailwindCSS IntelliSense does not work in `compoundVariants` despite the first element of the array.

### ISSUE THREAD

**Issue by its-monotype** [joe-bell/cva#108]
**Describe the bug**
IntelliSense does not work in `compoundVariants` despite the first element of the array in VSCode.

**To Reproduce**
1. Complete each step described in the README in "Installation -> TailwindCSS -> IntelliSense -> Visual Studio Code" section.
2. Try to use IntelliSense in the `compoundVariants` in any object despite the first one.

**Expected behavior**
IntelliSense work as expected as here:
![image](https://user-images.githubusercontent.com/79363260/216441025-5adeacd0-ffb2-47fb-8046-4aa953f2750c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/79363260/216439477-a9f9a9b5-f885-4885-8a97-3ccd06cf65fd.png)

**Comment by joe-bell** [comment]
Closing as this probably belongs in https://github.com/joe-bell/cva/discussions/85 – thanks for raising
