### ISSUE TITLE
Typescript error: using name 'ClassProp' from external module cannot be named

### ISSUE THREAD

**Issue by douglaseggleton** [joe-bell/cva#12]
**Describe the bug**
Typescript compiler complains that `ClassProp` cannot be named.

**To Reproduce**
Use `cva` as part of a type export.

```ts
import { cva, VariantProps } from 'class-variance-authority'

const classProps = cva('badge pa-2')

export type BadgeVariants = VariantProps<typeof classProps>
```

Typescript error:

```
Exported variable 'classProps' has or is using name 'ClassProp' from external module "node_modules/class-variance-authority/dist/index" but cannot be named.
```

**Expected behavior**
Typescript should not complain.

**Screenshots**

<img width="624" alt="Screenshot 2022-02-20 at 12 36 55" src="https://user-images.githubusercontent.com/1008377/154844155-47364329-7e8a-48c5-9f22-a903adfeda11.png">

**Additional context**
I *think* `ClassProp` is just missing an export.

**Comment by joe-bell** [comment]
Hey! See https://github.com/joe-bell/cva/issues/5

I think you perhaps need to add `skipLibCheck` or double-check your `tsconfig.json` file
