### ISSUE TITLE
Have 'activated' variant for button.

### ISSUE THREAD

**Issue by Tobjoern** [joe-bell/cva#130]
I created a standard button using cva, with various intents, like 'primary', 'light', 'activatable' etc.
Now I'm using a button, to open a dropdown menu. When the menu is opened, I'd like to have the button in an 'activated' state, i.e. the 'active:' pseudoselector should be enabled. Ideally I would have a prop like 'isActivated' on the btn component.

But how would I go about activating the 'active' pseudoselector? From my understanding, it is only possible to pass in strings to the individual variants, but ideally I would define states, like 'hovered', 'activated' etc. separately, so I can trigger them from JS.

**Comment by joe-bell** [comment]
You can achieve this; just create a CSS class for your `active:` state, and pass that string into your `isActivated` variant

Closing as this doesn't conform to the issue template
