### ISSUE TITLE
ESM Modules contains reference to a non-existing source map file

### ISSUE THREAD

**Issue by pfried** [joe-bell/cva#147]
**Describe the bug**

In version 0.5.2 the `main.mjs` contains a map reference which does not exist causing map generators to fail:

Line 51 `//# sourceMappingURL=index.mjs.map`

**To Reproduce**

Generate a sourcemap using modules and a map generator

**Expected behavior**
Either no sourceMappingURL or an `index.mjs.,map` file

**Comment by joe-bell** [comment]
Thanks for digging into this, I'll take a proper look when I have a moment 🙏

**Comment by joe-bell** [comment]
Closed by #148

**Comment by pfried** [comment]
thanks for merging, I can confirm the issue is solved
