### ISSUE TITLE
fontWeight applied with `className` props won't work for specific values

### ISSUE THREAD

**Issue by fernandoeeu** [joe-bell/cva#153]
**Describe the bug**
When passing custom `className` to a react CVA component, some `className`s won't take precedency against variants values.

**To Reproduce**

1. Create a react component using CVA;
2. Receive custom className as props;
3. Pass a valid tailwind-css prop that should override some tailwind-css class being used with base cva function, in this case the prop being passed is `font-bold`, that should translate to `font-weight: 700`. But the `font-semibold` of the base component won't be override.

**Expected behavior**
The final css should be `font-weight: 700`

**Screenshots**
CVA setup
![image](https://user-images.githubusercontent.com/43551523/234981340-7e3868fe-929a-4943-b32a-bbfde459af17.png)

Component being instantiated and the `font-bold` props being passed;
![image](https://user-images.githubusercontent.com/43551523/234981089-3a856eae-4070-4890-a676-543fc5fa2443.png)

CSS that wont work
<img width="174" alt="image" src="https://user-images.githubusercontent.com/43551523/234981516-73d23d12-9f4b-4537-b891-2aa012d6694f.png">

When passing other props, it works
<img width="148" alt="image" src="https://user-images.githubusercontent.com/43551523/234981693-35760e3b-1005-4357-a987-c096d2fc2241.png">

**Desktop (please complete the following information):**

- OS: Mac OS Ventura 13.1
- Browser Arc Browser
- Version Arc 0.100, Chromium 112.0.5615.137

**Smartphone (please complete the following information):**

- Device: iPhone 13 pro max
- OS: iOS 16.4.1
- Browser safari
- Version latest

**Comment by joe-bell** [comment]
Check out https://cva.style/docs/installation#handling-style-conflicts 😊
