### ISSUE TITLE
Incorrect type inference of variants and compound variants

### ISSUE THREAD

**Issue by Pablets** [joe-bell/cva#169]
**Describe the bug**

Incorrect type inference of variants and compound variants.

**To Reproduce**

1. Declare variants
```typescript
const buttonVariants = cva('w-fit', {
  variants: {
    variant: {
      primary: ['before:-z-10'],
      secondary: ['hover:bg-transparent'],
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});
``` 
2. Implement a component with those variants:

```typescript
...

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button: React.FC<ButtonProps> = ({ className, variant, ...props }) => (
  <button
    className={twMerge(buttonVariants({ variant, className }))}
    {...props}
  />
);
...
``` 
3. variant is of type 
```typescript
variant?: "primary" | "secondary" | null | undefined
``` 

**Expected behavior**

Type must be `variant?: "primary" | "secondary"` or `variant: "primary" | "secondary"`

**Screenshots**
<img width="692" alt="image" src="https://github.com/joe-bell/cva/assets/48801172/b97565bd-306f-461f-a242-d61cfbc6cd51">

**Additional context**
typescript 5.0.4

**Comment by Pablets** [comment]
I'm not sure but can it be because of this? I'm doing more research to discard if it's an isolated issue.

https://github.com/joe-bell/cva/blob/fd051cd1a262bec1698b3f4b80e7554fbda13366/packages/class-variance-authority/src/index.ts#L32
and 
https://github.com/joe-bell/cva/blob/fd051cd1a262bec1698b3f4b80e7554fbda13366/packages/class-variance-authority/src/index.ts#L34-L39

**Comment by joe-bell** [comment]
The explicit `null` is an intentional API decision which was carried over from Stitches.js:
https://cva.style/docs/api-reference#parameters

It will be removed in `cva@1.0` (https://github.com/joe-bell/cva/pull/113) so I'll close this for now
