### ISSUE TITLE
Typescript Autocomplete

### ISSUE THREAD

**Issue by stembrino** [joe-bell/cva#170]
# Typescript autocomplete is not working as expected
1. I'm using CVA in my components to generate variant classes, for example:
```ts
import { cva } from "class-variance-authority";
import styles from "./SlotButton.module.css";

export const variants = cva(styles.base, {
  variants: {
    variant: {
      primary: styles.primary,
      secondary: styles.secondary,
    },
    size: {
      small: styles.small,
      medium: styles.medium,
      large: styles.large,
    },
  },
  compoundVariants: [{ variant: "primary", size: "medium" }],
  defaultVariants: {
    variant: "primary",
    size: "medium",
  },
});
```
2. I'm importing the variants to my interface file to extend it as the documentation suggests:
```ts
import { type VariantProps } from "class-variance-authority";
import { variants } from "./SlotButton.variants";

export interface SlotButtonProps extends VariantProps<typeof variants> {
  label: string;
  rounded?: boolean;
  width?: string;
  color?: string;
  ariaLabel?: string;
  onClick: (event: React.MouseEvent<HTMLDivElement>) => void;
}
```

3. When using a value as default in my component the autocomplete is working:
![Screenshot from 2023-06-15 12-34-11](https://github.com/joe-bell/cva/assets/39069413/8bab9ac1-4987-4249-bbe6-dfccd7bebfbf)

4. (NOK) When importing components in some applications the autocomplete is not working as expected, example:
```tsx
<SlotButton label='Fancy Label' onClick={handleOnClickButton} size="[VSC IS NOT SUGGEST THE AUTOCOMPLETE]" />
// The size is a prop that is being set in a variant
```
## :camera:
NOK: don't get the autocomplete props
![image](https://github.com/joe-bell/cva/assets/39069413/66978183-5297-4e15-8ea4-918a3a49fc53)

NOK: don't get the value of the props
![image](https://github.com/joe-bell/cva/assets/39069413/fd715229-a98f-4aab-8fde-4d1cd7e782f2)

**Comment by vnva** [comment]
I have a similar problem. Have you solved it?

**Comment by vnva** [comment]
Adding the base parameter solves the problem

![image](https://github.com/joe-bell/cva/assets/57404657/eb0cbedc-d2b9-4a9d-af3d-1ec858fd0d10)
