### ISSUE TITLE
Attribute shorthand not working in Vue

### ISSUE THREAD

**Issue by hungify** [joe-bell/cva#178]
**Describe the bug**

I fork an example on your website and also found a bug about [Attribute shorthand bindings](https://eslint.vuejs.org/rules/prefer-true-attribute-shorthand.html)

In Vue, I pass `loading` to the prop but I get an empty string `loading = '' ` instead of a boolean. It is completely fine in React.

You can open Reproduced below and will see that.

I don't understand, Why is there such a difference between `disabled: ButtonProps["disabled"] ` and ` expanded: boolean | undefined | null;`

![image](https://github.com/joe-bell/cva/assets/78008509/c4dd1593-2268-486b-b871-6a535db677e2)

**To Reproduce**
https://stackblitz.com/edit/joe-bell-cva-qb58mc?file=src%2FApp.vue

**Expected behavior**
If I pass `loading` to prop, the component will receive `loading = true`

**Comment by joe-bell** [comment]
Sorry, please could you be more specific? I’m struggling to understand the problem here 🙏🏼

**Comment by joe-bell** [comment]
Right OK I see, thank you! Seems like very much a genuine bug with `boolean`s. I'll do some digging and consider as part of this:
https://github.com/joe-bell/cva/discussions/79
