### ISSUE TITLE
clsx default import is causing error with webpack 5

### ISSUE THREAD

**Issue by bbpcoforge** [joe-bell/cva#182]
export const cx = clsx;
With webpack 5 
const cx = clsx__WEBPACK_IMPORTED_MODULE_0__;

return cx(base, getVariantClassNames, getCompoundVariantClassNames, props === null || props === void 0 ? void 0 : props.class, props === null || props === void 0 ? void 0 : props.className);

cx is not a function because of default import of  clsx
import clsx from "clsx";

this should be like this
import {clsx} from "clsx";

Error:
index.mjs:47 Uncaught (in promise) TypeError: cx is not a function
    at eval (index.mjs:47:16)

Can you please help me to resolve this ASAP.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joe-bell** [comment]
Please can you provide a reproduction

**Comment by joe-bell** [comment]
There are too many factors at play here and to be honest I think if your Webpack 5 configuration can't support a default export then there's probably something faulty upstream – so for now I'll be closing this. Hope you figure something out!
