### ISSUE TITLE
TS: ClassProp is an ambiguous union that causes type errors

### ISSUE THREAD

**Issue by akomm** [joe-bell/cva#202]
**Describe the bug**
The union used for `ClassProp` is relying on optional props:
```ts
type ClassProp = {
    class: ClassValue;
    className?: never;
} | {
    class?: never;
    className: ClassValue;
} | {
    class?: never;
    className?: never;
};
```

You can not reliably discriminate based on optional properties if multiple elements of union have the discriminated property `optional`. This is why the error is raised in the below linked TS Playground example:
```
Argument of type 'ComponentProps' is not assignable to parameter of type 'ClassProp | undefined'.
  Type 'ComponentProps' is not assignable to type '{ class?: undefined; className: ClassValue; }'.
    Property 'className' is optional in type 'ComponentProps' but required in type '{ class?: undefined; className: ClassValue; }'
```

**To Reproduce**
Just open and see the error in [TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwGoEMrBQOxgBShMAZwBo4BjANxQF84AzfEOAIjIBsVDCBaK9LMgFNuKAK4wAFtGAwAnswBQCshEyF4K8KsHY4AXnJUAFAG0AugEolcsILgBhCFsw7c+Ivrip+2PAUIAPDaCEHTkTpAu2AB8cABkiApwyeQcXAByKCCCAPwAXHDq6JgA5grUSgD0lXDAmOHOrnkKACaC7Gh2KmrwYO6EBY6Nvv1VNR0ZWYJ6CJqRrkZ9-hYVc9rYi-0WQA)

**Expected behavior**
No type error

**Screenshots**

**Desktop (please complete the following information):**

not relevant, type error

**Smartphone (please complete the following information):**

not relevant, type error

**Additional context**

Here is how to fix the `ClassProp` type:
[TS Playground](https://www.typescriptlang.org/play?#code/PTAEGMBsGcA9QKawC4CcCG5kEsD2A7AKEOQE8AHBUAYUnWmgDV1IBXKgXhroYEFUMpUAB9u9aABFsWPPnSoho6Gmz4A5iND5WAWwBGCVJu2RImvblyQE6fJtb4AJggBmqhI4DcJClVripGQJ5IS4AJQRwXFRHAB5lVFU1ABpQW1IAPm8ySjE+AXRQvKYWdgBtAF1vQhAIADd0UDdYYmAAKhqwaOw1VRZQAFpQPVRcAGsEOx9c-wYABVHyUC4Ab0JQDYgeaAAuYuY2BG9NrfEAOXQdBAB+PfwEOsNvAF9NNZOocVutB6f1zc+DAuVz2sxKhxeb3+G0B0G+90eqGOAO2wJud1+SMIz28bWArRAHVqzQ80z82wWuCWq2hpwY3zBB3YyJhqMu6J+iMhoneKK+GK5tNhaIZ2yZR2xnTxxBcDiCdmQCGUYMp5FiABVEChJo5oMVVRkABTkRa7UDqgCUoBWz2Izk+qCoUXwylAJqp0AAjHsVsL2d8Eklbfa6I6IARXe7yNAAEw+2EBlTqYORUNOiPIN2mgDM8bZINAgeThBD8nTLszUegABY8+I9kW1CmHeXI6aAKx1hgNpMpOnQNE9xLF0th51tj0ANi7cKHSVSfoLjebafDFazHoA7DO5+oF-mOcuS6my2uJ9GABw7wu9-fnf27psE0A6XCsaAIAa4RGgZC4QsIFQyAABZUKoLiGI6ji-r4oC4C45rPtAwFvpA0H4LgmaQdEJBKsgKqLMapqelatSaqsi6Hr29hOK47iOLairKhShFVjGpFgOR1oJo+NHOG49wMbhzHiKqREetmHHmss3EHo+jF4QRVLidG1ZSVxvrbPJSEoawaGIAIOFMfhLHKVW7YWsJJmiaxpqTpZxlKeQKnQJuDmKaZzlVheFpAA)

**Comment by joe-bell** [comment]
Hey! This is an intentional API design decision

1. You should be using `class` **or** `className` – **not both**

    _e.g. if you're using React.js the `className` prop will be more familiar/relevant_
    
2. You should extract the types via [`VariantProps`](https://cva.style/docs/getting-started/typescript), not `ComponentProps`

   _`className` or `class` aren't included in these types because `cva` doesn't make assumptions about your preferred framework. There are [plenty of examples](https://github.com/joe-bell/cva/tree/main/examples) in the repo to showcase how to achieve type typings you're looking for._
   
✌️

**Comment by joe-bell** [comment]
@akomm apologies for prematurely closing, appreciate the fix and will add in `cva@beta` 🙏
