### ISSUE TITLE
[Typescript] TS2345 - Not assignable to type undefined (CVA expect undefined)

### ISSUE THREAD

**Issue by Baben01** [joe-bell/cva#209]
**Describe the bug**
I'm trying to build a solution based on typescript and CVA. 
But I have an issue when using a custom Type / Object that looks like what CVA expect but it seems that inference are not working. 

CVA expect `undefined` instead of my custom type. 

**To Reproduce**
You can easily reproduce by copying this code snippet : 

```typescript
import { cva } from "cva";
type ButtonVariants = {
  variant: {
    primary: string;
    secondary: string;
    tertiary: string;
  };
  disabled: {
    true: string;
  };
};

const buttonVariants: ButtonVariants = {
  variant: {
    primary: "string",
    secondary: "string",
    tertiary: "string",
  },
  disabled: {
    true: "string",
  },
};

type Wrapper<T> = {
  base: string;
  variants?: T;
};

const buttonSchema: Wrapper<ButtonVariants> = {
  base: "test",
  variants: buttonVariants,
};

const button = cva(buttonSchema);
/* 
Argument of type 'Wrapper<ButtonVariants>' is not assignable to parameter of type 'CVAConfigBase & { variants?: undefined; compoundVariants?: undefined; defaultVariants?: undefined; }'.
  Type 'Wrapper<ButtonVariants>' is not assignable to type '{ variants?: undefined; compoundVariants?: undefined; defaultVariants?: undefined; }'.
    Types of property 'variants' are incompatible.
      Type 'ButtonVariants | undefined' is not assignable to type 'undefined'.
        Type 'ButtonVariants' is not assignable to type 'undefined'.ts(2345)
*/
```
**Expected behavior**
No error should be triggered by Typescript and the type inference should work as expected

**Additional context**
`"cva": "^1.0.0-beta.1"`
`"typescript": "^5.1.6"`

**Comment by joe-bell** [comment]
Hey! This is intended behaviour I’m afraid — you cannot customise the config/schema type 

`cva` is designed to be the source of truth, much like for example you would use `zod`. However, I know it’s not that easy to extract out the raw config (e.g. for Storybook) right now

You are using the `beta` release so please be aware that this API may change for the better ☺️

If you have any more feedback for the `beta` release, please feel free to leave notes [in the discussion](https://github.com/joe-bell/cva/discussions/205)

**Comment by Baben01** [comment]
Hello, 

Thanks for your response :D
