### ISSUE TITLE
Boolean variants that do not specify both `true` and `false` result in an awkward type

### ISSUE THREAD

**Issue by brattonross** [joe-bell/cva#21]
**Describe the bug**
When creating a boolean variant, if only one state is given as a key, the type of the variant prop in the resulting function will not accept the other state. For example a boolean variant that only implements `true` will result in the function only accepting `true | undefined`. This, in my opinion, is awkward to work with, as you're likely going to be passing a boolean component prop into your function to generate the class name.

**To Reproduce**

```jsx
import { cva } from "class-variance-authority";

const button = cva(null, {
  variants: {
    disabled: {
      true: ['bg-gray-300']
    }
  }
});

function Button({ disabled }: { disabled?: boolean; }) {
  const className = button({
    disabled // Type 'boolean' is not assignable to type 'true'
  });
  return <button className={className}>Hi</button>;
}
```

Note that if you implement the other state in the variant (even if it doesn't actually do anything), then the expected type becomes `boolean | undefined`, so as a work around something like this seems to be okay:

```jsx
import { cva } from "class-variance-authority";

const button = cva(null, {
  variants: {
    disabled: {
      true: ['bg-gray-300'],
      false: []
    }
  }
});

function Button({ disabled }: { disabled?: boolean; }) {
  const className = button({ disabled });
  return <button className={className}>Hi</button>;
}
```

**Expected behavior**
I appreciate that its a bit of a nit-pick, but personally I think it would make the library more friendly to use if boolean variants always accepted `boolean | undefined`, even if there is no implementation for one of the boolean states. This way you can pass boolean props from components straight to cva without a typing issue.

**Comment by joe-bell** [comment]
Cheers for this! I’ve noticed another bug recently with Boolean variants so I’ll see if I can tackle this at the same time (but can’t guarantee when this will be due to life commitments)

**Comment by brattonross** [comment]
Absolutely, no rush, I'm also happy to try my hand at contributing 😄 I've made a PR with the changes that I would make to solve this, see what you think when you've got some time

**Comment by joe-bell** [comment]
Thank you!
