### ISSUE TITLE
Cannot find module 'class-variance-authority/dist/types'

### ISSUE THREAD

**Issue by damianfrizzi** [joe-bell/cva#231]
**Describe the bug**
I'm currently in the midst of migrating several internal applications to TypeScript's `"moduleResolution": "bundler"` setting. Within our organization, we maintain a crucial component library that's utilized across various applications. This library relies on the awesome cva package (thanks a lot for this 🙏 ). Unfortunately, we've encountered a type issue as we transition to the new bundler module resolution.

**To Reproduce**
1. Clone [this minimal reproduction](https://github.com/damianfrizzi/cva-types-issue) and run `yarn build`
2. Use an existing React TypeScript project (or create a new one) with `"moduleResolution": "bundler"` in `tsconfig.json`
3. Use yarn link (or similar) to create a symlink to the cloned repository
4. Insert the following code somewhere in the render tree of your application:
```
import { Button } from "cva-types-issue";
...
<Button>Test</Button>
...
```

If you type check (`tsc`) the project you will receive the following error:
```
../../cva-types-issue/dist/src/components/Button/Button.d.ts:6:12 - error TS2307: Cannot find module 'class-variance-authority/dist/types' or its corresponding type declarations.

} & import("class-variance-authority/dist/types").ClassProp) | undefined) => string;
```

**Expected behavior**
The cva build output should contain the correct type definitions/type exports to support `"moduleResolution": "bundler"`.
Ideally, no change in userland should be required.

**Additional context**
Related issues:
- https://github.com/joe-bell/cva/discussions/143
- https://github.com/joe-bell/cva/issues/190

Related PR's:
- Might be the reason [this PR](https://github.com/joe-bell/cva/pull/229) was created.

**Comment by joe-bell** [comment]
Hey @damianfrizzi! Appreciate the detailed write up 🙏 

Please can you do me a huge favour and try using [`cva@beta`](https://beta.cva.style) instead? Do you still see the issue?

That'll help me determine next steps

**Comment by damianfrizzi** [comment]
Hey @joe-bell, I appreciate the speedy response! Just gave cva@beta a whirl, and everything seems to work 🎉. Thanks a bunch for your help!

**Comment by joe-bell** [comment]
Amazing! In that case I'll close this PR. Thanks again 🙏
