### ISSUE TITLE
Package name `cva` is available at `npmjs`

### ISSUE THREAD

**Issue by uceumice** [joe-bell/cva#234]
Hey, I found `class-variance-authority` to be quite a long name for a tool that otherwise could be written in only 3 letters. Currently [place held](https://www.npmjs.com/package/cva#readme) name `cva` is 'available', as stated in its README.md.

Have there been any ideas going that direction?

**Comment by joe-bell** [comment]
See the docs (written directly under the installation command)
https://cva.style/docs/getting-started/installation
