### ISSUE TITLE
TS - Class prop type is too limiting

### ISSUE THREAD

**Issue by chenasraf** [joe-bell/cva#241]
**Describe the bug**

Using an optional `className` prop causes TS error:

```
Argument of type 'PipelineChartProps' is not assignable to parameter of type '(ConfigVariants<{}> & ClassProp) | undefined'.
  Type 'PipelineChartProps' is not assignable to type 'ConfigVariants<{}> & { class?: undefined; className: ClassValue; }'.
    Type 'PipelineChartProps' is not assignable to type '{ class?: undefined; className: ClassValue; }'.
      Property 'className' is optional in type 'ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>' but required in type '{ class?: undefined; className: ClassValue; }'. [2345]
```

**To Reproduce**

[See reproducible sandbox](https://codesandbox.io/p/sandbox/new-dust-4pm2pp?file=%2Fsrc%2FApp.tsx%3A44%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp46qlcm000a3b6eps9ai2s6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp46qlcm00033b6eatc3mtbh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp46qlcm00073b6e8i7mvutm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp46qlcm00093b6evheu6t1e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp46qlcm00033b6eatc3mtbh%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00033b6eatc3mtbh%2522%252C%2522activeTabId%2522%253A%2522clp46rjy3010v3b6eyaat8drt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00023b6e22gqm2pb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp46qpgb007a3b6eattes2qs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clp46rjy3010v3b6eyaat8drt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp46qlcm00093b6evheu6t1e%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00093b6evheu6t1e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00083b6exh2eu5kp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp46qlcm00083b6exh2eu5kp%2522%257D%252C%2522clp46qlcm00073b6e8i7mvutm%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00073b6e8i7mvutm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00043b6e9qs3mpl1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp46qlcm00053b6eq5a9g1b5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clp46qlcm00063b6ewohc4pfk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%252C%257B%2522id%2522%253A%2522clp46w1mj01ci3b6efw0jgg4r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp46w1ug00c1efip3ddo97gd%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp46qlcm00043b6e9qs3mpl1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Create a component with the following boilerplate code:

```ts
import { cva } from 'class-variance-authority'

type PipelineChartProps = {
  className?: string
}

const pipelineChartVariants = cva([], {
  variants: {},
})

export default function PipelineChart(props: PipelineChartProps) {
  const { className, ...rest } = props
  const pipelineChartCls = pipelineChartVariants(props) // <----- error
  return (
    <div className={pipelineChartCls}>
      PipelineChart
    </div>
  )
}
```

The error above will appear for the TS checking

**Expected behavior**

The prop `className` should be allowed to be optional, often this pattern is used to allow **optional** overrides from a parent component. In the case above, the className prop must be mandatory for the TS check to work.

**Screenshots**

![image](https://github.com/joe-bell/cva/assets/167217/c032eaa6-9ead-48c0-bd2d-c9e221e357db)
![image](https://github.com/joe-bell/cva/assets/167217/2e8daf8c-51ac-4782-bd63-961755a2ba9e)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Arc
- Version: latest (`0.7.0`)

**Comment by joe-bell** [comment]
I've honestly never run into this error before so I am very confused, I don't think I can help much more with a reproduction I'm afraid

If that fails, please also try [`cva@beta`](https://beta.cva.style)

**Comment by chenasraf** [comment]
Hi @joe-bell, thanks for looking into it.

I have managed to reproduce this on [this codesandbox](https://codesandbox.io/p/sandbox/new-dust-4pm2pp?file=%2Fsrc%2FApp.tsx%3A44%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp46qlcm000a3b6eps9ai2s6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp46qlcm00033b6eatc3mtbh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp46qlcm00073b6e8i7mvutm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp46qlcm00093b6evheu6t1e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp46qlcm00033b6eatc3mtbh%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00033b6eatc3mtbh%2522%252C%2522activeTabId%2522%253A%2522clp46rjy3010v3b6eyaat8drt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00023b6e22gqm2pb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp46qpgb007a3b6eattes2qs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clp46rjy3010v3b6eyaat8drt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp46qlcm00093b6evheu6t1e%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00093b6evheu6t1e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00083b6exh2eu5kp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp46qlcm00083b6exh2eu5kp%2522%257D%252C%2522clp46qlcm00073b6e8i7mvutm%2522%253A%257B%2522id%2522%253A%2522clp46qlcm00073b6e8i7mvutm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp46qlcm00043b6e9qs3mpl1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp46qlcm00053b6eq5a9g1b5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clp46qlcm00063b6ewohc4pfk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%252C%257B%2522id%2522%253A%2522clp46w1mj01ci3b6efw0jgg4r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp46w1ug00c1efip3ddo97gd%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp46qlcm00043b6e9qs3mpl1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). You can see the TS error on line 49.

I also added the link on the original post for easier reference.

**Comment by joe-bell** [comment]
Everything seems to be working as expected for me? 🤔 

![CleanShot 2023-11-20 at 08 25 48@2x](https://github.com/joe-bell/cva/assets/7349341/e7c81eb7-8310-418b-9192-31e30b1c8e9d)

Follow-up question:
1. Why not use `React.ComponentProps<ELEMENT>`?
2. [Is your VSCode TypeScript version using the "Workspace" version?](https://stackoverflow.com/a/39676463)

Unfortunately not much I can do to help if I can't recreate it I'm afraid, sorry!

**Comment by joe-bell** [comment]
Closing as I haven't heard back and can't recreate. Hope you manage to get this solved!
