### ISSUE TITLE
Conditional variants based on other variants

### ISSUE THREAD

**Issue by Sicria** [joe-bell/cva#249]
Is it possible to define a different class set based on one of the variants?

Eg. If a button has the below classes, is it possible for `rounded` to define a new set of classes for `size` so that if you provide `rounded` it could use something like `sm: 'p-3'` so that it is actually rounded.

Currently to achieve this you'd have to do something like `<Button rounded className="p-3">` which makes the `size` somewhat useless.

```
const buttonVariants = cva(
  'block',
  {
    variants: {
      size: {
        sm: 'py-2 px-3',
        md: 'py-3 px-4',
        lg: 'p-4 sm:p-5',
      },
      rounded: {
        true: 'rounded-full',
      },
    },
    defaultVariants: {
      size: 'sm',
    },
  },
);
```

Maybe I'm missing something and this is already possible though?

**Comment by joe-bell** [comment]
https://cva.style/docs/getting-started/variants#compound-variants
