### ISSUE TITLE
impossible combinations

### ISSUE THREAD

**Issue by abernier** [joe-bell/cva#262]
imagine a button with variants
- intent=filled,outline,text
- theme=danger,pretty,candy
- size=unset,small

but with some combinations should not be supported (by design team), for instance: intent=text/theme=candy

how would you prevent/handle those cases so TS yells at:

```tsx
<Button intent="text" theme="candy" />
```

**Comment by joe-bell** [comment]
https://github.com/joe-bell/cva/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L11
