### ISSUE TITLE
prevent single compoundVariant

### ISSUE THREAD

**Issue by abernier** [joe-bell/cva#263]
Currently, it is possible (without any TS warning) to use `compoundVariants` with a single prop:

```
cva("base", {
  variants: {}
  compoundVariants: [
    {
      size: "big",
      css: "..."
    }
  ]
})
```

IMO it should go into `variants` if only one prop like here.

What about adding type-safety to prevent this?

**Comment by joe-bell** [comment]
https://github.com/joe-bell/cva/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L11
