### ISSUE TITLE
[Feature request] Styles conditional upon other styles

### ISSUE THREAD

**Issue by nukeop** [joe-bell/cva#264]
Let's say I have a cva style defined like this:

```typescript
const contextMenuItem = cva(
    'flex',
    {
        variants: {
            intent: {
                warning: 'text-red-500',
            },
            active: {
                true: 'bg-stone-100',
            },
        },
    },
);
```

So now I'd like to do something like this: if `active` is set to `true`, then `intent` with the value of `warning` should also apply `bg-red-100` in addition to the style shown here. Is it possible, using the library in its current state?

**Comment by nukeop** [comment]
Nvm, I realized compound variants can do that. Thanks for thinking of everything.

**Comment by elbasan** [comment]
how did you manage to do this? i'm struggling to come up with a solution when on dark mode
