### ISSUE TITLE
Null type is adding to the variants 

### ISSUE THREAD

**Issue by webappcoding** [joe-bell/cva#270]
Hey 

Please refer this below image 

<img width="1033" alt="Screenshot 2024-02-24 at 12 54 34 AM" src="https://github.com/joe-bell/cva/assets/71024109/010014d3-85bc-4f3b-980e-588361c1b973">

When i am removing the "null" from here 

<img width="859" alt="Screenshot 2024-02-24 at 1 02 47 AM" src="https://github.com/joe-bell/cva/assets/71024109/54568950-03aa-41b2-98a1-4d628b75a325">

Every thing is working fine as expected

<img width="1012" alt="Screenshot 2024-02-24 at 1 01 49 AM" src="https://github.com/joe-bell/cva/assets/71024109/be2d555b-d231-4163-8945-e2a01c6fd32e">

**Comment by joe-bell** [comment]
Closing as this [doesn't correspond to the issue template](https://github.com/joe-bell/cva/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L11), [`null` will be removed in `cva@1.0`](https://beta.cva.style/getting-started/whats-new/#3-goodbye-null), and this is likely a Storybook issue not a `cva` issue
