### ISSUE TITLE
TW Intellisense doesn't work when trying to use `cva` with generic params

### ISSUE THREAD

**Issue by kapobajza** [joe-bell/cva#285]
Hello.

**Describe the bug**
Intellisense doesn't work when trying to use `cva` with generic type params.

**To Reproduce**

1. Follow the steps to [enable autocompletion in the docs](https://cva.style/docs/getting-started/installation#intellisense)
2. Try using `cva` with generic type params:

```typescript
type InputVariant = "primary" | "secondary";

type InputVariantConfig = {
  variant: Record<InputVariant, string>;
};

const inputVariants = cva<InputVariantConfig>(
  "border-input bg-background", // Intellisense doesn't work here
  {
    variants: {
      variant: {
        primary: "bg-primary", // Intellisense doesn't work here
        secondary: "bg-secondary" // Intellisense doesn't work here
      }
    }
  }
)
```
If I remove the `<InputVariantConfig>` generic type param, it works as expected.

**Expected behavior**
Intellisense should be working even when adding generic type params

**Desktop (please complete the following information):**

- OS: **macOS**
- Browser: **Brave**
- Version: **1.65.114 Chromium: 124.0.6367.60**

**Additional context**
I found a solution for this and I'll create a PR to address it.

**Comment by joe-bell** [comment]
Hey! `cva` isn't designed to accept generic parameters. `cva@1.0` will make this clearer
