### ISSUE TITLE
cva config can't suggestion key(variants, etc..) when create cva value

### ISSUE THREAD

**Issue by jiwon79** [joe-bell/cva#296]
**Describe the bug**
When create cva value with config, it can't suggestion keys(variants, defaultVariants, compoundVariants)

**Expected behavior**
I want that IDE can suggestion keys(variants, defaultVariants, compoundVariants) and warning only type is wrong.

**Screenshots**
<img width="339" alt="Screenshot 2024-06-09 at 3 38 32 PM" src="https://github.com/joe-bell/cva/assets/59159410/60d9d1d6-2ab3-4fc4-9e5b-d1f6d576205b">

- OS: macOS
- IDE: visual studio code

**Comment by joe-bell** [comment]
I can't recreate this, I think there may be some other issues at play here

In the meantime, please try using [`cva@1.0`](http://beta.cva.style)

Thanks!
