### ISSUE TITLE
Allow compoundVariants to map key -> combination of variants, that is then accessible through a compoundVariant prop.

### ISSUE THREAD

**Issue by moodiest** [joe-bell/cva#37]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The compoundVariants property should allow an object to be provided to it. The object can contain keys that each map to a combination of variants. These keys can then be used on components using a `compoundVariant="primary"` prop, for example.

**Describe alternatives you've considered**
Giving every variant class set I define the same name (e.g. primary, secondary, tertiary), so that my component can fill in the property variant names if I use a compoundVariant prop.

**Additional context**
My thought process behind this is that you may wish to use pre-defined combinations of your variants without specifying each one every time. You should be able to specify a single prop on your component that refers to a combination of the variants. To me, this use case would make sense for compoundVariants.

I'm not sure if I'm misunderstanding how compoundVariants should work, but this is how I would have thought it should work.

Nonetheless, I feel like this would be a pretty useful feature to add.

**Comment by joe-bell** [comment]
Yeah I think maybe there's some misunderstanding here: compound variants should only apply if two or more variant conditions are met

If you need a one-off variant, I recommend a standard variant

If you need to share styles between, I recommend storing classes in a separate array and spreading to each definition
