### ISSUE TITLE
ClassProp interface not exported

### ISSUE THREAD

**Issue by essejmclean** [joe-bell/cva#5]
**Describe the bug**
When using cva in a Typescript file (i.e. `style.ts`) setting a constant using `cva` throws an error that the library is looking for an external interface called `ClassProp`.

**To Reproduce**
I imported `class-variance-authority` into a Next.js project with Typescript enabled and began using `cva`.

**Expected behavior**
No errors - expect the `ClassProp` interface to be exported.

**Screenshots**
<img width="686" alt="Typescript error" src="https://user-images.githubusercontent.com/21248254/153455546-b97ef4d2-86f4-4f63-937f-c9d92b1acba1.png">

**Additional context**
I've made a pull request that fixes the problem by exporting the `ClassProp` interface, ran tests, and tested by configuring it as a local package in a monorepo. Works like a charm now.

**Comment by essejmclean** [comment]
@joe-bell I just debugged my `tsconfig.json` and it was configured wonky. Much appreciated for asking me to go back over that again. Apologies for any wasted time on your end. This library is hugely helpful!

**Comment by joe-bell** [comment]
@essejmclean no worries at all! Glad to hear you got it resolved

**Comment by douglaseggleton** [comment]
Thanks for pointing me in the right direction 🙏🏻

I can reproduce with the following set in `tsconfig.json` (declaration only).
See https://codesandbox.io/s/cva-issue-5-repro-forked-2wzw7m?file=/tsconfig.json:145-202

```json
{
  "compilerOptions": {
     "emitDeclarationOnly": true,
     "declaration": true,
   }
}
```
