### ISSUE TITLE
No typescript warnings when variant is missing

### ISSUE THREAD

**Issue by hugotiger** [joe-bell/cva#52]
**Describe the bug**
Typescript not complaining when variant is missing. I'm thinking this should even throw an error since it's a missing parameter by the looks of it. At least to me the `variants` should be mutually exclusive (like an XOR gate in lack of a better word to describe it).

When `defaultValue` is passed the prop being optional makes sense to me (like it is now).

**To Reproduce**
```ts
const buttonStyles = cva('base-styles', {
  variants: {
    intent: {
      primary: 'primary-styles',
      secondary: 'secondary-styles',
    },
  },
})

// @ts-expect-error - No `intent` prop passed
const className = buttonStyles()
```

**Expected behavior**
I would expect the prop to be required if no `defaultVariant` is set. Either that or that `defaultVariant` should always be required (although I think that API would be less flexible).

**Additional context**
Also it seems as VSCode Intellisense works better if you add a constraint to `cva`'s generic:

```ts
export const cva =
  <T extends ConfigSchema>(base?: ClassValue, config?: Config<T>) => ...
```
Is there any special reason why you use conditional types instead? I'm really curious as I'm trying to get better with advanced types :)

**Comment by joe-bell** [comment]
Hey @hugotiger! Appreciate you putting time into writing this up, but I'm afraid it's not a behaviour I'm planning to change

I get your argument, I just don't agree with the assumption that "anything without a default should be required", and it goes against the idea of keeping `cva` relatively unopinionated

I'd prefer to keep these sort of decisions to the consumer for now:
https://github.com/joe-bell/cva#required-variants

_but maybe there's a way to make this easier_
