### ISSUE TITLE
Feature Request: cva without base parameter

### ISSUE THREAD

**Issue by marklawlor** [joe-bell/cva#57]
Currently `cva = <T>(base?: ClassValue, config?: Config<T>) => (props?: Props<T>) => string`.

It would be great if there was an overloaded version which simply accepted `cva = <T>(config?: Config<T>) => (props?: Props<T>) => string`.

**Comment by joe-bell** [comment]
Please follow [the issue template](https://github.com/joe-bell/cva/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L14)
