### ISSUE TITLE
Support for "nested" variants (e.g. primary[neutral=true])

### ISSUE THREAD

**Issue by TmLev** [joe-bell/cva#68]
I have a use case where I have multiple variants of the button (primary/secondary/flat) and an additional boolean flag for "neutrality". Essentialy I'm looking for a way to achieve something like this:
```js
const button = cva(["font-semibold", "border", "rounded"], {
  variants: {
    intent: {
      primary: {
        display: 'flex', // Same for neutral and not.
        backgroundColor: neutral ? 'white' : 'blue', // Depends on `neutral`.
      },
    }
  }
})
```

Obviously, one can create multiple variants (`primary-neutral` and `primary-not-neutral`), but this leads to quite a lot of repetition if variants differ in a few properties only.

**Comment by joe-bell** [comment]
> **Warning**
>
> This issue does not follow the repo's issue template

---

This is supported via [`compoundVariants`](https://www.nngroup.com/articles/hostile-error-messages/)

```ts
const button = cva(["font-semibold", "border", "rounded"], {
  variants: {
    intent: {
      primary: "flex",
    },
    neutral: {
      false: null,
      true: null,
    },
  },
  compoundVariants: [
    { intent: "primary", neutral: false, class: "bg-white" },
    { intent: "primary", neutral: true, class: "bg-blue-300" },
  ],
});
```
