### ISSUE TITLE
Variants giving errors with Typescript

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [joe-bell/cva#69]
**Describe the bug**
The `cva` function type gives errors when trying to pass in the variants object

**To Reproduce**

1. Use cva and create a component

**Expected behavior**
The error should not be happening. There could be a generic that will be passed onto the function to then accept the parameters.

**Screenshots**
<img width="688" alt="Screenshot 2022-11-21 at 22 44 49" src="https://user-images.githubusercontent.com/74371045/203216411-078239a0-954a-4e0f-9d1b-24625e6135ae.png">

**Desktop (please complete the following information):**
- OS: MacOS
- Browser Arc (Chromium based)

**Smartphone (please complete the following information):**
- Not using

**Additional context**

**Comment by joe-bell** [comment]
Hiya, please can you provide the code instead of a screenshot?

**Comment by joe-bell** [comment]
Hey! `cva` isn't generic, you can't pass types into it (e.g. `cva<YourType>`)

The intention for `cva` is to be a "single source of truth" and I don't plan to change that. If you get stuck please don't hesitate to create a discussion!
