### ISSUE TITLE
bug: config argument - '{}' is not assignable to parameter of type 'undefined' (TypeScript error)

### ISSUE THREAD

**Issue by kamiloox** [joe-bell/cva#75]
**Describe the bug**

When I was trying out the `cva`, I noticed that the type `Config` doesn't have proper TypeScript support. The second argument in the function can be either `Config<T>` or `undefined` and it's fine, but when I tried to pass an empty object without any key I received an error.
![image](https://user-images.githubusercontent.com/45523480/205468314-6b87c8a8-7ac1-410c-ae9e-b253d7bf341c.png)

I checked the type of a Config and it has every field marked as optional. So I thought that I don't have to pass anything and the empty object should be working, but actually, it didn't (as in the previous screenshot).
![image](https://user-images.githubusercontent.com/45523480/205468532-ce56433a-fb72-4403-8099-f2296f378a91.png)

**To Reproduce**

1. Import `cva` function
2. Use `cva` function with any first argument that satisfies the type (even empty string), and for the second argument pass an empty object - `cva('', {});`
3. Hover over a function and you will see a TypeScript error - `Argument of type '{}' is not assignable to parameter of type 'undefined'`

**Expected behavior**
The typeScript should be showing what fields could I have in the config and not show the error when the object is empty (as every field is marked as optional in the type). Example of expected behavior:
![image](https://user-images.githubusercontent.com/45523480/205468662-1f266ae5-e801-4562-8cc1-135a0885620a.png)

**Additional context**

Currently, this is not working, because of TypeScript when trying to check if `T extends ConfigSchema` needs to have a `variant` field defined in the `Config`. So without that, the generic `T` is not assigned to anything. It exists but it points to nothing.
![image](https://user-images.githubusercontent.com/45523480/205468864-fc83d839-0d3b-410f-85b4-f1a341aece80.png)

This issue could be easily resolved by passing a default value for a generic in `cva` function.
![image](https://user-images.githubusercontent.com/45523480/205468829-e6f95427-4505-4a7d-bc1b-c38ea65f5a13.png)

**Comment by joe-bell** [comment]
Appreciate you making the time to raise this, but it seems like a trivial issue IMO – I don't know why you'd need to pass an empty object 🤷

**Comment by joe-bell** [comment]
@kamiloox apologies, I can see what you're saying now. I'll go ahead and implement, thanks for your suggestion
