### ISSUE TITLE
Is it possible to get a group of class strings instead of a single output string?

### ISSUE THREAD

**Issue by devrsi0n** [joe-bell/cva#86]
Hi folks, I love the idea of this project, it really resolved the long class string issue with tailwindcss.

I have a question about how to get a group of class strings instead of a single output string? For example, I have a prop to a group strings map, thus I can apply individual classes to each element,
<img width="453" alt="image" src="https://user-images.githubusercontent.com/7880675/211178050-9050b4d8-1baa-4fcc-9743-8d189275b974.png">

Not sure if this is possible, thank you for your time.

**Comment by joe-bell** [comment]
I'm afraid not, sorry
