### ISSUE TITLE
required/optional API suggestions from docs don't adhere to top level API signatures

### ISSUE THREAD

**Issue by lifeiscontent** [joe-bell/cva#91]
**Describe the bug**
The docs say optional / required variants are a thing, but from what I can tell, the TypeScript types are either wrong, or the API currently only supports string/array variants of the API and not a nested object signature.

**To Reproduce**

1. Go to [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYwG4EM4F84DMoQhwDkyANugM6UC0GUw6AdsgKY3oCuMAFtMDACexANwAoMawAekWCghNK8AELcYCuAF4UGABRi4cAEQATVri5kYRgDQHE9w-UZMYlAFwPD3uFFYBHTmA-E08ERx84AElXVlcwxwBIZLAGEHQoQU8jSkJWWzFkxMpWZAUTDKzjXmAmAHNbSMMInyw7JraWuAgwGGAFdDIEpsMAZWAAL1ZhkZ9KdLIh43mIMiMuwywuztb27DsAShEgA)
2. See error

**Expected behavior**
using the prescription from the docs here https://github.com/joe-bell/cva#required-variants
I would expect it to support the same top level API of objects/arrays/strings

**Screenshots**

**Desktop (please complete the following information):**

- OS: Kubuntu Linux
- Browser Chrome
- Version 109.0.5414.74

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joe-bell** [comment]
As the [docs](https://github.com/joe-bell/cva#required-variants) state: 

> To keep the API small and unopionated, cva **doesn't offer** a built-in solution for setting required variants.

The example shows how to `pick` and `omit` specific props to create the required effect – there is no `required` feature
