### ISSUE TITLE
Compound Variants merging issue

### ISSUE THREAD

**Issue by sean-brydon** [joe-bell/cva#95]
**Describe the bug**
I'm not 100% sure if this is a bug or i'm just expecting this to work differently.
Repo: https://github.com/calcom/cal.com/commit/68957ef1839dca0df2e5aadd065d8c465117c8c3

 We have defined variants - ones we will be focusing on is variant and size. 
<img width="921" alt="CleanShot 2023-01-17 at 15 01 55@2x" src="https://user-images.githubusercontent.com/55134778/212933471-64199b37-1a40-4ee4-aae5-45a229a31381.png">

Created a compound variant that targets both of these 
<img width="417" alt="CleanShot 2023-01-17 at 15 03 43@2x" src="https://user-images.githubusercontent.com/55134778/212933765-0fe6ab89-9419-4170-9349-37b511f2eb82.png">

**To Reproduce**
See above

**Expected behavior**
I would expect the class to come out as icon + base + className in variant but for the variant classname to take priority without having to do `!p-2`

**Comment by joe-bell** [comment]
Hey! You're absolutely right to expect `icon + base + className` and that **is** what's happening here.

The problem you're hitting into is that Tailwind's shorthand padding classes are likely defined before the directional padding classes (not something we can customize). So you will unfortunately need to bump the specificity here to override

Alternatives you could try:
- Use arbitrary values and store the padding value as a [custom property](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties)

  `[--padding-small:8px] p-[var(--padding-small)]`

- Use [`tailwind-merge`](https://github.com/joe-bell/cva#tailwind-css) to handle style conflicts
